### ISSUE TITLE
Prepend the TapSigHash tag when doing k256 Schnorr signatures?

### ISSUE THREAD

**Issue by faultymajority** [RustCrypto/elliptic-curves#1031]
Just learned that BIP341/342 expect messages to be prefixed with two copies of `sha256("TapSigHash")` before signing.
More of a question: Should the `k256::schnorr::SigningKey` implementations of `Signer` and friends automatically do this double prefixing? As we already have an implementation for `tagged_hash("TapSigHash")`.

**Comment by tarcieri** [comment]
The construction implemented is the one described in BIP340, which actually specifies the Schnorr signature construction we implement.

BIP341/BIP342 are application-level implementation details which go beyond the signature algorithm itself.

I'll note at least some of the domain separation performed is expected to be independent of and usable across multiple signature algorithms:

https://github.com/bitcoin/bips/blob/master/bip-0341.mediawiki#rationale

> Why is the input to hash<sub>TapSighash</sub> prefixed with 0x00? This prefix is called the sighash epoch, and allows reusing the hash<sub>TapSighash</sub> tagged hash in future signature algorithms that make invasive changes to how hashing is performed (as opposed to the ext_flag mechanism that is used for incremental extensions). An alternative is having them use a different tag, but supporting a growing number of tags may become undesirable.

We could potentially include an example or helper method for computing hash<sub>TapSighash</sub>, but as these aren't specified along with the signature algorithm itself in BIP340 it doesn't feel like something that should be added by default.
