### ISSUE TITLE
Pre-release of k256 v0.14?

### ISSUE THREAD

**Issue by dvdplm** [RustCrypto/elliptic-curves#1051]
It looks like there's a `v0.14-pre.0` branch heading in this direction but it's not available on crates.io just yet. Can I do anything to help to make that happen? :)

**Comment by tarcieri** [comment]
I can cut a prerelease

**Comment by dvdplm** [comment]
Lovely, thank you very much.

**Comment by tarcieri** [comment]
Released in #1054
