### ISSUE TITLE
sm2: Support for SM2PKE

### ISSUE THREAD

**Issue by heliannuuthus** [RustCrypto/elliptic-curves#1067]

**Comment by heliannuuthus** [comment]
@tarcieri  I can provide an implementation of SM2PKE, but please let me know what the conventions or specifications :)

**Comment by tarcieri** [comment]
@heliannuuthus the spec is linked from here: https://github.com/RustCrypto/elliptic-curves/tree/master/sm2#about-sm2

I'm not terribly familiar with it but can review a PR to add it.

**Comment by heliannuuthus** [comment]
I'll give it a try.

**Comment by heliannuuthus** [comment]
> @heliannuuthus the spec is linked from here: https://github.com/RustCrypto/elliptic-curves/tree/master/sm2#about-sm2
> 
> I'm not terribly familiar with it but can review a PR to add it.

I'll give it a try.
