### ISSUE TITLE
Porting secp256k1 implementation to ESP32S3 (Xtensa architecture)

### ISSUE THREAD

**Issue by SafetyMustHave** [RustCrypto/elliptic-curves#1073]
Dear RustCrypto team,

I'm working on porting the secp256k1 implementation to the ESP32S3 microcontroller, which uses the Xtensa architecture. I'm seeking advice on the following:

1. Strategies for adapting the existing secp256k1 Rust implementation to the Xtensa architecture.
2. Potential performance optimizations for running secp256k1 on a resource-constrained device like ESP32S3.
3. Memory usage considerations and optimization techniques for this specific use case.
4. Handling of any architecture-specific challenges that might arise.

Specific questions:
- Are there any known issues with running the current secp256k1 implementation on non-standard architectures like Xtensa?
- What modifications, if any, might be necessary to ensure optimal performance on ESP32S3?
- Are there any ESP32S3-specific features we should be aware of that could benefit (or hinder) the secp256k1 implementation?

Any guidance, examples, or resources you could provide would be immensely helpful. Thank you for your expertise and support!

**Comment by tarcieri** [comment]
`k256` is pure Rust. It should work on any 32-bit or 64-bit target. It's been written with `no_std` support.

As far as improved performance, it would likely need inline assembly for hotspots. See #55 as an existing tracking issue for that.
