### ISSUE TITLE
Take a look on my crate 

### ISSUE THREAD

**Issue by ranxiverba** [RustCrypto/elliptic-curves#12]
[Rac](https://github.com/ranxiverba/rac) For now there is AEAD, but, I'll remove it. Maybe you will find some for yours.

**Comment by tarcieri** [comment]
Thanks. It seems like you may be able to leverage some of the traits from this crate as we develop them, although for things like scalar and field arithmetic like you have here:

https://github.com/ranxiverba/rac/blob/master/src/elliptic.rs

...we will probably use the built in Rust arithmetic traits (e.g. `core::ops::{Add, Mul}` in a similar manner to how curve25519-dalek leverages these traits.
