### ISSUE TITLE
How to obtain public key from a secret key?

### ISSUE THREAD

**Issue by devashishdxt** [RustCrypto/elliptic-curves#14]
I'm not able to find any way to get public key corresponding to any secret key. Is there a way to obtain it?

**Comment by tarcieri** [comment]
The relevant mathematical function is fixed-base scalar multiplication.

This project contains a crate-per-elliptic curve, and none of them implement scalar multiplication.

Thus I will leave this issue open, noting @str4d has in fact contributed an immaculately written field arithmetic backend for the NIST P-256 elliptic curve, with the caveat that he purposefully was trying to solve the specific problems of point compression and decompression.

**Comment by tarcieri** [comment]
The `p256` and `k256` crates now both support scalar multiplication.

The next steps here, I think, are to define traits which generically provide access to fixed-base scalar multiplication.

I opened an issue about that here: https://github.com/RustCrypto/elliptic-curves/issues/22

**Comment by tarcieri** [comment]
This was fixed in #49 

When the `arithmetic` backend is enabled for a particular curve, `PublicKey::from_secret_key` is available.

I might do some refactoring to change that to `SecretKey::compressed_public_key()` and `SecretKey::uncompressed_public_key()`
