### ISSUE TITLE
Scalar::sqrt unimplemented

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/elliptic-curves#170]
The [`Field`](https://docs.rs/ff/0.7.0/ff/trait.Field.html) trait implementation has a `todo!()` stub for [`Field::sqrt`](https://docs.rs/ff/latest/ff/trait.Field.html#tymethod.sqrt) in the following crates:

- [ ] `k256`
- [ ] `p256`

**Comment by Pratyush** [comment]
FWIW we have generic impls of these in algebra: https://github.com/scipr-lab/zexe/blob/38e792fffc78c0bfc4d780ee21257c8cb70a2e2a/algebra-core/src/fields/arithmetic.rs#L247

**Comment by str4d** [comment]
We have generic constant-time sqrt implementations in `ff_derive` for `p = 3 mod 4` and `p = 
1 mod 16`: https://github.com/zkcrypto/ff/blob/dcdc2ad3ae1ff50ea689f76bbb667d575cf2a3ff/ff_derive/src/lib.rs#L500-L577
