### ISSUE TITLE
p256/k256: release v0.2.0

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/elliptic-curves#23]
Now that both the `p256` and `k256` crates have point/field arithmetic implementations, it'd be good to cut a new release.

I'm fine with cutting a new release based on what's currently on `master` (and following up on issues like #22 after that). If there aren't any objections, I can go ahead and do that.

cc @str4d @tuxxy

**Comment by tuxxy** [comment]
I just realized that `scalar` in both crates is private. Do we intend on keeping that?

**Comment by tarcieri** [comment]
Good question. Perhaps they could be made `pub` for now?

**Comment by tuxxy** [comment]
Sounds good to me. Any objections @str4d?

**Comment by tarcieri** [comment]
I opened a PR which re-exports the `Scalar` types as `pub` along with a number of small documentation fixups here: https://github.com/RustCrypto/elliptic-curves/pull/25

**Comment by tarcieri** [comment]
These were released last month.
