### ISSUE TITLE
Improve secp256k1 field multiplication speeds

### ISSUE THREAD

**Issue by tuxxy** [RustCrypto/elliptic-curves#24]
Presently, the `k256` crate implements montgomery mulmod for multiplication/reduction. @hdevalence brought up a point in #19 that there may be a method that leverages the special form of the secp256k1 modulus to improve multiplication performance.

Performance of a scalar multiplication for the `k256` crate:
```
test tests::k256_scalar_mul    ... bench:     197,252 ns/iter (+/- 2,838)
```
It would be nice to see a significant performance increase for this.

**Comment by tarcieri** [comment]
@tuxxy would you consider this addressed by #59?

**Comment by tuxxy** [comment]
Not quite. I'd like to write some benchmarks for myself and talk with @fjarri a bit before it gets closed.

**Comment by fjarri** [comment]
What multiplication are we talking about here? Scalar-scalar, field-field, or point-scalar? The latter can certainly be improved, I'm planning to look into it.

Where's this benchmark you're quoting, by the way?

**Comment by tuxxy** [comment]
I've unfortunately lost the benchmark I originally wrote, but it measured point-scalar. It would be nice to see two benchmarks, 1) comparing point-scalar operations to `libsecp256k1` and 2) measuring scalar-scalar operations (maybe against a variety of implementations?).

**Comment by tarcieri** [comment]
I think we can go ahead and close this out. Further optimizations would certainly be appreciated, but I think we're ok for now.
