### ISSUE TITLE
std feature should specify ecdsa/std but does not

### ISSUE THREAD

**Issue by prestwich** [RustCrypto/elliptic-curves#271]
`ecdsa/std` is missing from the `std` feature. As a result, the `Error` type does not `impl std::error::Error` when the `std` feature is selected

**Comment by prestwich** [comment]
ack, this was meant for `k256`, not here 🤦‍♀️

**Comment by tarcieri** [comment]
This is one of those cases where it'd sure be nice to have [weak dependency activation](https://github.com/rust-lang/cargo/issues/8832).

But yeah, for now we can make `std` activate `ecdsa/std`.

**Comment by tarcieri** [comment]
I took a look at this, and it's actually really annoying without weak feature activation.

Right now `k256` and `p256` enable the `std` feature by default, so at the very least this would also mean `ecdsa` is activated by default.

**Comment by tarcieri** [comment]
`k256` and `p256` v0.7.2 now activate `ecdsa/std` when `std` is activated
