### ISSUE TITLE
Create VerificationKey from 65 byte uncompressed pubkey

### ISSUE THREAD

**Issue by webmaster128** [RustCrypto/elliptic-curves#291]
I'm not familiar with SEC-1 encoding for public keys, so I hope I don't get this horribly wrong. But as far as I understand SEC-1 encoding is DER encoded format.

Is it also possible to create a  [VerificationKey](https://docs.rs/k256/0.7.2/k256/ecdsa/struct.VerifyingKey.html) from a 65 byte 0x04 prefixed public key (Ethereum format) or 0x02/0x03 prefixed compressed public key (Cosmos SDK format)?

See also https://github.com/bitcoin-core/secp256k1/blob/24d1656/include/secp256k1.h#L329-L348

**Comment by tarcieri** [comment]
0x02/0x03/0x04-prefixed keys are in SEC1 format, and a 65-byte 0x04-prefixed key is the uncompressed format, yes (they aren't DER-encoded, but similar to DER in terms of use of a tag byte)

You can decode SEC1-encoded public keys in uncompressed or compressed form (or even the identity `0x00`) using the `VerifyingKey::from_sec1_bytes` method, which works on any SEC1-encoded public key: https://docs.rs/k256/0.7.2/k256/ecdsa/struct.VerifyingKey.html#method.from_sec1_bytes

**Comment by webmaster128** [comment]
Merci, this is very helpful
