### ISSUE TITLE
k256: Schnorr/Taproot (BIP-340) support

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/elliptic-curves#381]
This is a tracking issue for supporting the new Schnorr signature algorithm proposed in BIP-340:

https://github.com/bitcoin/bips/blob/master/bip-0340.mediawiki

**Comment by tarcieri** [comment]
WIP implementation: #482

**Comment by tarcieri** [comment]
Obsoleted by #554

**Comment by elichai** [comment]
> @elichai that was fixed in #1041

Thanks! I tried searching for Issues/PRs mentioning this but for some reason did not find that one :)
