### ISSUE TITLE
ecdsa signing algorithm ?

### ISSUE THREAD

**Issue by adrian798** [RustCrypto/elliptic-curves#40]
is there any scope to add ecdsa signing algorithm ?

**Comment by tarcieri** [comment]
We definitely plan on adding ECDSA relatively soon. See the existing ECDSA crate:

https://github.com/RustCrypto/signatures/tree/master/ecdsa

The main issues to tackle are support for curve arithmetic which is generic over the underlying (Weierstrass) curve (#22) as well as access to the underlying (x-)coordinate(s) for `AffinePoint`s in a safe, misuse-resistant way.

**Comment by tarcieri** [comment]
FYI, just landed a secp256k1 ECDSA implementation in #79.

There's also an open PR for P-256 which I'd like to take a swing at fixing up: #57

**Comment by tarcieri** [comment]
As of #101 and #104, ECDSA (with random `k` only at present) is fully implemented.

#105 added initial documentation to the `k256` crate.

Going to go ahead and close this issue. There's still more work to do, but that will happen mostly upstream in the `ecdsa` crate.
