### ISSUE TITLE
Exposing FieldElement?

### ISSUE THREAD

**Issue by randombit** [RustCrypto/elliptic-curves#439]
We're interested in supporting hash2curve for k256 and p256 but these require arithmetic on field elements (*not* scalars), and the field elements are not exposed.

**Comment by tarcieri** [comment]
Thus far we've deliberately avoided exposing field elements in order to provide a misuse resistant API.

For hash2curve specifically my suggestion would be [defining traits for hash2curve in the `elliptic-curve` crate](https://github.com/RustCrypto/traits/issues/481) and then implementing them directly in `k256`/`p256`.

**Comment by str4d** [comment]
I agree with @tarcieri. I would definitely like to see a hash-to-curve trait (either in `group` or `elliptic-curve`) that can provide this functionality, and if the hash-to-field component of the ID proves to be more widely-useful, then a trait to that effect could end up in `ff`.

**Comment by randombit** [comment]
Wouldn't this effectively require implementing SSWU and related logic twice, once for each curve?

**Comment by tarcieri** [comment]
You should be able to define it as e.g. a generic function somewhere like `elliptic-curve`

**Comment by tarcieri** [comment]
Another approach that might work for abstracting SSWU would be to define a trait (e.g. `Sswu`) intended to be impl'd on a curve-specific `FieldElement` type, which has a `map_to_curve_simple_swu` function with a default impl and an associated curve-specific `const Z`.

Then all curve-specific impls of that trait would need to do is define `Z`.

**Comment by tarcieri** [comment]
Generic optimized SWU has been added upstream to the `elliptic-curve` crate: https://github.com/RustCrypto/traits/pull/854
