### ISSUE TITLE
[Question] k256: How to verify a with metamask signed message?

### ISSUE THREAD

**Issue by chriamue** [RustCrypto/elliptic-curves#455]
Hi, I signed a message with Metamask on the Kovan Network.
Now I try to verify this signature based on this test: https://github.com/RustCrypto/elliptic-curves/blob/90412fe7bf002dce1cb7cb8cc4c689895b85068c/k256/src/ecdsa/recoverable.rs#L342

```rust
    #[test]
    fn test_verify() {
        use hex_literal::hex;
        use k256::{
            ecdsa::{recoverable::Signature},
            EncodedPoint,
        };

        let account = hex!("63f9a92d8d61b48a9fff8d58080425a3012d05c8");
        let message = b"0x63f9a92d8d61b48a9fff8d58080425a3012d05c82kl75awln2l";
        let signature = hex!("7097b9a0810d13e60182f261708c2c260e86ea09853cd48b184a5a4b4ea08c02087bd86b8cdee3aec88ac365ec533c9a111e5b5586c4941a790ca46970c3f3801c");
        //let signature = hex!("46c05b6368a44b8810d79859441d819b8e7cdc8bfd371e35c53196f4bcacdb5135c7facce2a97b95eacba8a586d87b7958aaf8368ab29cee481f76e871dbd9cb01");

        println!("signature len: {}", signature.len());

        let sig = Signature::try_from(&signature[..]);
        println!("sig: {:?}", sig);
        let pk = sig.unwrap().recover_verify_key(message).unwrap();
        assert_eq!(&account, EncodedPoint::from(&pk).as_bytes());
    }
```

Running the tests I get an error at `sig.unwrap()` as sig is an Err here.
(The commented signature works with `Signature::try_from(&signature[..])`

```sh
cargo test web3::tests::test_verify -- --nocapture
running 1 test
signature len: 65
sig: Err(signature::Error {})
thread 'web3::tests::test_verify' panicked at 'called `Result::unwrap()` on an `Err` value: signature::Error {}', src/web3.rs:75:22
```

What I already found out here
https://github.com/RustCrypto/elliptic-curves/blob/90412fe7bf002dce1cb7cb8cc4c689895b85068c/k256/src/ecdsa/recoverable.rs#L280
is, that the 65th byte in the signature must 0 or 1, which is 'c' in this example.

I read some texts that this recovery id is also based on the chain id, but I have no idea, how to get the right byte here.

Maybe someone has an idea how to solve it, or must other values than 0 and 1 also be allowed?

Thanks,
Christian

**Comment by tarcieri** [comment]
> I read some texts that this recovery id is also based on the chain id, but I have no idea, how to get the right byte here.

I don't know anything about MetaMask offhand. I have heard there are alternative encodings for the "recid", in which case you'll need to figure out what encoding is being used and use it to correctly instantiate `k256::ecdsa::recoverable::Id`.

There should be 2 or 4 possibilities. This library supports 2 of the 4, i.e. recid `0` or `1` (the other two possibilities don't occur in practice outside of contrived examples)
