### ISSUE TITLE
Typenum for an uncompressed curve point size?

### ISSUE THREAD

**Issue by rozbb** [RustCrypto/elliptic-curves#541]
I used to be able to do `sec1::UncompressedPointSize<NistP256>`, but `UncompressedPointSize` was removed. I might be missing something, but it looks like there isn't a way of getting the size of an uncompressed point at a type/const level.

**Comment by tarcieri** [comment]
It's now an associated type of `sec1::ModulusSize`:

https://docs.rs/sec1/latest/sec1/point/trait.ModulusSize.html#associatedtype.UncompressedPointSize

This was needed to decouple `sec1` from the `elliptic-curve` crate.

**Comment by rozbb** [comment]
Yeah, I saw that but couldn't see it implemented for anything relevant. I just figured it out, but it's somewhat nonintuitive: `<FieldSize<NistP256> as ModulusSize>::UncompressedPointSize`

**Comment by tarcieri** [comment]
Yeah, it’s not ideal, but hopefully one of those things that can be improved after const generics.

It was difficult to find a clean way to decouple `sec1` from the `elliptic-curve` crate.

If you have any ideas, we’ll probably be making another release with breaking changes soon.
