### ISSUE TITLE
diffie_hellman with permanent keys

### ISSUE THREAD

**Issue by dustinbraun** [RustCrypto/elliptic-curves#555]
Hi,

is there a way to do diffie-hellman (P256) with permanent public and secret keys?

**Comment by tarcieri** [comment]
You'll need to use the low-level Diffie-Hellman API:

https://docs.rs/elliptic-curve/0.12.0/elliptic_curve/ecdh/fn.diffie_hellman.html

Perhaps it should be re-exported from `p256::ecdh` (and `k256::ecdh`)
