### ISSUE TITLE
K256: panic 'attempt to shift left with overflow' in mul_shift_vartime

### ISSUE THREAD

**Issue by d86leader** [RustCrypto/elliptic-curves#624]
I've been playing around with the private functions in the crate, and found a strange panic:

```rust
fn main() {
    let bytes = [
        45, 222, 176, 90, 248, 2, 34, 102, 207, 238, 243, 208, 108, 43, 55, 13, 250, 22, 24, 237,
        0, 136, 157, 70, 80, 246, 95, 108, 229, 181, 119, 57,
    ];
    let s1 = k256::Scalar::from_bytes_unchecked(&bytes);
    let bytes = [
        0xac, 0x9c, 0x52, 0xb3, 0x3f, 0xa3, 0xcf, 0x1f, 0x5a, 0xd9, 0xe3, 0xfd, 0x77, 0xed, 0x9b,
        0xa4, 0xa8, 0x80, 0xb9, 0xfc, 0x8e, 0xc7, 0x39, 0xc2, 0xe0, 0xcf, 0xc8, 0x10, 0xb5, 0x12,
        0x83, 0xcf,
    ];
    let s2 = k256::Scalar::from_bytes_unchecked(&bytes);
    let r = k256::arithmetic::scalar::wide::WideScalar::mul_shift_vartime(&s1, &s2, 256);
    println!("{:?}", r.to_bytes());
}
```
gives:
```
thread 'main' panicked at 'attempt to shift left with overflow', k256/src/arithmetic/scalar/wide64.rs:84:21
```

S2 here is the g1 constant from scalar decomposition.
This doesn't happen with shift value of 257 or more, so possibly a problem with an incorrect assertion at the top of `mul_shift_vartime` function?

In any case, it seems impossible to trigger this in real world since this function is private and only called with higher shift values, but might reflect a defect in implementation.

**Comment by tarcieri** [comment]
cc @fjarri 

I'm not terribly worried about this as it's an internal API as you mentioned, and generally one used with a constant parameter, but it is a little confusing it isn't being caught w\ `assert`

**Comment by fjarri** [comment]
Not sure yet what is happening exactly, but from reading the original libsecp256k1 code I found out that they changed the algorithm to bump the decomposition precision: https://github.com/bitcoin-core/secp256k1/commit/76ed922a5f09d63e0622825ca83d9301c1ef3efe . Might be worth it to port those changes.
