### ISSUE TITLE
Ethereum signing

### ISSUE THREAD

**Issue by rhobro** [RustCrypto/elliptic-curves#625]
Hi there,

I am trying to sign some messages for Ethereum.

I have been doing this previously using the `secp256k1` crate with the `sign_ecdsa` method. However, that crate seems to be Rust bindings to a C library. I learnt that the `k256` crate was a pure rust alternative and have been trying to migrate to it.

However, it seems to be generating different signatures (which don't work) to `secp256k1`, so I wanted to check I am calling the right methods.

Currently, I am parsing a hex string into a `SecretKey` which I then convert into a `SigningKey` with
```rust
let signing_key = SigningKey::from(&self.eth_private);
```
Then I'm signing the hash of a method with
```rust
signing_key.sign(hash)
```

Is this equivalent to `secp256k1`'s
```rust
let msg = Message::from_slice(hash).expect("invalid hash to sign");
self.secp.sign_ecdsa(&msg, &self.eth_private)
 ```?

Thanks

**Comment by tarcieri** [comment]
Ethereum uses "recoverable" ECDSA signatures which include an additional "recovery ID" which can be used to recover the public key from the signature. It also defaults to using Keccak256 as the hash function.

They're implemented in this module: https://docs.rs/k256/latest/k256/ecdsa/recoverable/index.html

**Comment by rhobro** [comment]
That's really useful. Thank you.

Out of interest, the docs say that it's enabled only for the feature "ecdsa-core"? Does feature "ecdsa" include "ecdsa-core"?

**Comment by rhobro** [comment]
And I've already hashed a message. How can I sign the hash without the function doing it again?

**Comment by tarcieri** [comment]
Yes, `ecdsa` enables `ecdsa-core`: https://github.com/RustCrypto/elliptic-curves/blob/master/k256/Cargo.toml#L47

To sign a prehashed message you'll need to use the low-level `hazmat` API: https://docs.rs/ecdsa/latest/ecdsa/hazmat/trait.SignPrimitive.html
