### ISSUE TITLE
Allow scalar from arbitrary size byte array using modular reduction

### ISSUE THREAD

**Issue by Plebshot** [RustCrypto/elliptic-curves#645]
## Problem

I am currently trying to replace some elliptic curve crypto using the [openssl crate](https://docs.rs/openssl/latest/openssl/) with p384. 

Given some arbitrary length data, I want create a valid point on the curve by simply interpreting said data as scalar and multiplying it with the curves identity (see example below). In openssl, due to the arbitrary length big integers, the resulting scalar may be larger than the curves order. This should be fine in terms of multiplication and result in a valid point on the curve non the less. 

Here I am running into issues due to the fixed sized nature of `p384::U384`. I tried to use `Scalar::from_be_bytes_reduced()`, hoping this could be achieved via modulo. However, this also seems to expect a fixed size byte array. 

Now, is there a way to translate the example below into `p384`? I couldn't didn't find any obvious way and also found no related issues to this. I am not entirely sure if this is even possible with fixed size integers.

## openssl example

```rust
use openssl::{bn::*,ec::*, nid::Nid, error::ErrorStack};

pub fn map_bytes_to_curve(bytes: &[u8]) -> Result<EcPoint, ErrorStack> {
    let mut ctx = BigNumContext::new()?;
    let curve = EcGroup::from_curve_name(Nid::SECP384R1)?;
    let as_bignum = BigNum::from_slice(bytes)?;
    let mut mapped = EcPoint::new(&curve)?;
    mapped.mul_generator(&curve, &as_bignum, &ctx)?;

    Ok(mapped)
}
```
Note that `EcPoint::mul_generator()` corresponds to [EC_POINT_mul](https://www.openssl.org/docs/man1.0.2/man3/EC_POINT_mul.html) which seems to be something different than `p384::Scalar::multiplicative_generator()`.

**Comment by tarcieri** [comment]
No, we don’t have an arbitrary precision type to make this work. If you really want to do it, you’ll need to use something like `num-bigint` to perform this kind of extra-wide reduction.

Also more generally I’d probably suggest using hash-to-scalar for this sort of operation.

**Comment by Plebshot** [comment]
Thank you for the info.

I was hoping that potentially an extra-wide reduction would be possible without an arbitrary size type in some form. But this is probably an upstream issue as well.

>  I’d probably suggest using hash-to-scalar for this sort of operation.

Are you referring to [hash2curve](https://docs.rs/elliptic-curve/latest/elliptic_curve/hash2curve/index.html)? I can't seem to find implementation for the `MapToCurve` trait or similar within `p384`

**Comment by tarcieri** [comment]
Hash-to-scalar can be as simple as hashing an input and performing a modular reduction on the hash
