### ISSUE TITLE
k256: How to get Uncompressed size of VerifiyingKey (PublicKey)

### ISSUE THREAD

**Issue by curiousdev04** [RustCrypto/elliptic-curves#661]
How to get the Uncompressed size of VerifyingKey(PublicKey) from the given SigningKey(PrivateKey), The default size of the VerifiyingKey is `33 byets`, but I need the uncompressed one e.g 64 or 65 bytes of the VerifiyingKey.

**Comment by tarcieri** [comment]
Use `ToEncodedPoint` with `compress: false`:

https://docs.rs/k256/latest/k256/ecdsa/struct.VerifyingKey.html#impl-ToEncodedPoint%3CSecp256k1%3E-for-VerifyingKey
