### ISSUE TITLE
Question: port https://crates.io/crates/secp256k1 to k256 for RFC6979 signing

### ISSUE THREAD

**Issue by gyuho** [RustCrypto/elliptic-curves#671]
I am trying to port my code in `secp256k1` to `k256`, and would appreciate if anybody can help find what I'm doing wrong.

The original code with https://crates.io/crates/secp256k1 does:

```rust
fn sign_digest(p: &secp256k1::SecretKey, digest: &[u8]) -> io::Result<key::secp256k1::signature::Sig> {
  assert_eq!(digest.len(), ring::digest::SHA256_OUTPUT_LEN);

  let secp = secp256k1::Secp256k1::new();
  let m = secp256k1::Message::from_slice(digest).map_err(|e| {
      Error::new(
          ErrorKind::Other,
          format!("failed secp256k1::Message::from_slice {}", e),
      )
  })?;

  let sig = secp.sign_ecdsa_recoverable(&m, &self.0);
  let (rec_id, sig) = sig.serialize_compact();

  let mut sig = Vec::from(sig);
  sig.push(rec_id.to_i32() as u8);
  assert_eq!(sig.len(), 65);

  let sig = k256::ecdsa::recoverable::Signature::try_from(b).map_err(|e| {
    Error::new(
      ErrorKind::Other,
      format!("failed to load recoverable signature {}", e),
    )
  })?;
```

And the ported code with `k256`:

```rust
fn sign_digest(p: &k256::SecretKey, digest: &[u8]) -> io::Result<key::secp256k1::signature::Sig> {
  assert_eq!(digest.len(), ring::digest::SHA256_OUTPUT_LEN);

  let signing_key = k256::ecdsa::SigningKey::from(p.clone());
  let sig: k256::ecdsa::recoverable::Signature = signing_key.sign(digest);
```

Both output the valid signatures but when I try retrieving the public key from two signatures, I get different results (using https://pkg.go.dev/github.com/decred/dcrd/dcrec/secp256k1/v4/ecdsa#RecoverCompact).

Any pointer would be appreciated!

Thanks!

**Comment by tarcieri** [comment]
The recovered public key should match the original public key / verifying key.

So which public key is it recovering and which one is matching / mismatching?

**Comment by tarcieri** [comment]
```rust
  let sig: k256::ecdsa::recoverable::Signature = signing_key.sign(digest);
```

This line is signing a *message*, not a message digest. The message is first hashed with Keccak256 in this case.

To sign a message digest, you need to use this trait:

https://docs.rs/signature/latest/signature/hazmat/trait.PrehashSigner.html

Both libraries are using RFC6979, so the resulting signatures should match.

Regardless of whether you're signing a message or a message digest, the same public key / verifying key should be recovered. You can compare the recovered key to the actual public key / verifying key for a given private key and see which one is a mismatch.

**Comment by gyuho** [comment]
@tarcieri Thank you so much, and prehash signer works! One more question, how do I verify this signature from the prehash signer? I assume when recovering the public key from the signature (output from sign_prehash), I cannot use `recover_verifying_key` because it's basically `self.recover_verifying_key_from_digest(Keccak256::new_with_prefix(msg))`?

**Comment by tarcieri** [comment]
You need [`Signature::recover_verifying_key_from_digest_bytes`](https://docs.rs/k256/latest/k256/ecdsa/recoverable/struct.Signature.html#method.recover_verifying_key_from_digest_bytes)

**Comment by gyuho** [comment]
[Signature::recover_verifying_key_from_digest_bytes](https://docs.rs/k256/latest/k256/ecdsa/recoverable/struct.Signature.html#method.recover_verifying_key_from_digest_bytes) was exactly what I needed.

Thank you again for the awesome project and all the help!
