### ISSUE TITLE
Implement `FromOkm` for `k256::Scalar`

### ISSUE THREAD

**Issue by survived** [RustCrypto/elliptic-curves#682]
`k256::Scalar` currently doesn't implement `FromOkm`, and because of that [`hash_to_scalar`] is not working.

Note that `p256::Scalar` does implement `FromOkm`, I expect that this implementation can be borrowed, as these are pretty much the same things.

[`hash_to_scalar`]: https://docs.rs/elliptic-curve/latest/elliptic_curve/hash2curve/trait.GroupDigest.html#method.hash_to_scalar

**Comment by tarcieri** [comment]
See #673
