### ISSUE TITLE
iter::Product and iter::Sum for Scalar

### ISSUE THREAD

**Issue by nickray** [RustCrypto/elliptic-curves#685]
I assume these are missing since nobody needed them so far, or is there a concern?

Doing a bunch of `iterator.fold(Scalar::ZERO, |acc, summand| acc + summand)` where I'd like to just write `iterator.sum()`.

Would also be nice to have Sum for AffinePoint.

**Comment by tarcieri** [comment]
Yeah. Kind of surprised there isn't a supertrait bound for at least `Sum` on `Field`

**Comment by str4d** [comment]
I think it's just that no one has asked for it before. I think it makes sense for `ff::Field` given that we already have the bound `group::Group: Sum`.

**Comment by tarcieri** [comment]
Added in #730
