### ISSUE TITLE
getSharedSecret()

### ISSUE THREAD

**Issue by mikedilger** [RustCrypto/elliptic-curves#687]
Is there a way I can replicate https://github.com/paulmillr/noble-secp256k1 getSharedSecret() function using this crate?

If not, can we add a function for that?  It's used in the nostr protocol.  It's basically a normalized public key multiplied by a normalied private key, but the devil is in the details (and if I try to write it, there will be even more devils in the details).

**Comment by tarcieri** [comment]
You're looking for https://docs.rs/k256/latest/k256/ecdh/fn.diffie_hellman.html

**Comment by mikedilger** [comment]
Thanks. Unfortunately I can't get a `SecretKey` from a `schnorr::SigningKey` on which to run `.to_nonzero_scalar()`, and I can't get a `NonZeroScalar` directly from a `schnorr::SigningKey` even though it is right in there privately. And if I try to go into bytes and back `let field_bytes = signing_key.to_bytes(); let nonzero_scalar = NonZeroScalar::from_repr(field_bytes)` the bounds are not satisfied.

Can we have a schnorr::SigningKey.inner() or something?

**Comment by tarcieri** [comment]
#690 adds an accessor method, however it's on the v0.12 release track and therefore won't be available until the next minor release

**Comment by mikedilger** [comment]
Thanks!  In the meantime I created an identical type into which I transmute.
