### ISSUE TITLE
primeorder: Implement (To/From)EncodedPoint for ProjectivePoint

### ISSUE THREAD

**Issue by survived** [RustCrypto/elliptic-curves#720]
I have noticed that `primeorder::ProjectivePoint` lacks of `ToEncodedPoint`/`FromEncodedPoint` traits implemented. `p256::ProjectivePoint` [did implement these traits in v0.11](https://docs.rs/p256/0.11.1/p256/struct.ProjectivePoint.html#impl-ToEncodedPoint%3CNistP256%3E), however since v0.12 these traits are dropped. Also `k256::ProjectivePoint` [does still implement these traits in v0.12](https://docs.rs/k256/latest/k256/struct.ProjectivePoint.html#impl-FromEncodedPoint%3CSecp256k1%3E-for-ProjectivePoint).

Is it possible to implement mentioned traits for `primeorder::ProjectivePoint`, or you intentionally dropped them?

**Comment by tarcieri** [comment]
It's an oversight and they can be added back
