### ISSUE TITLE
Unable to verify signature following upgrade of p256 library from version 0.11.1 to 0.12.0 

### ISSUE THREAD

**Issue by mattjpowell** [RustCrypto/elliptic-curves#727]
Following the upgrade of the **p256** elliptic curve library from version 0.11.1 to 0.12.0 we have encountered an error when verifying signatures using the sample code linked below:
https://github.com/RustCrypto/elliptic-curves/blob/2e79f417933687b0dd7d773676b642c1054932a5/p256/src/ecdsa.rs#L38

The error returned is:
![image](https://user-images.githubusercontent.com/48388390/214892883-2c9087f7-c4a1-4a89-9610-3ea3834abc6f.png)

Our current code does the verify as follows

```
    #[test]
    fn test_signature_validation() {
        // Signing
        let keys = SigningKey::random(&mut OsRng);
        let message = b"ECDSA proves knowledge of a secret number in the context of a single message";
        let ec_signature :Signature = keys.sign(message);

        // Verification
        let public_key = VerifyingKey::from(&keys);
        assert!(public_key.verify(message, &ec_signature).is_ok());
    }
```
The imports we have are:

```
    use p256::ecdsa::signature::{Signer, Verifier};
    use p256::ecdsa::{Signature, SigningKey};
    use p256::elliptic_curve::rand_core::OsRng;
    use p256::{EncodedPoint, U256};
    use p256::ecdsa::signature::hazmat::PrehashVerifier;
    use p256::elliptic_curve::generic_array::GenericArray;
    use p256::ecdsa::VerifyingKey;
```

Any suggestions on what we should change to make this work following the upgrade would be gratefully appreciated please.

**Comment by tarcieri** [comment]
This is the important part of the error message:

```
the trait `p256::ecdsa::signature::Verifier<&ecdsa::Signature<NistP256>>` is not implemented
```

This makes it look like you're passing `&&Signature<NistP256>>` as the `signature` argument to `verify`, although confusingly it doesn't look like that's what's happening in your code example.

Try changing  `public_key.verify(message, &ec_signature)` to `public_key.verify(message, ec_signature)` and see if that fixes your problem.

Also check your code against the example at: https://docs.rs/p256/latest/p256/ecdsa/index.html#signingverification-example

That example is doctested in CI and known to be working.

**Comment by mattjpowell** [comment]
@tarcieri Thank you very much for the quick response, that has resolved the issue.

Apologies for what now appears quite a silly mistake on our part, but we are still quite new to Rust.

The library is working well for us in our tests so far.
