### ISSUE TITLE
p256+p384: missing `PrimeField` constants

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/elliptic-curves#731]
There are TODOs added in #730 to define the following constants of the `PrimeField` trait:

## `p256`
- [x] `field.rs`
  - [x] `DELTA`
- [x] `scalar.rs`
  - [x] `DELTA`

## `p384`

- `field.rs`
  - [x] `TWO_INV`
  - [x] `ROOT_OF_UNITY_INV`
  - [x] `DELTA`
- `scalar.rs`
  - [x] `TWO_INV`
  - [x] `ROOT_OF_UNITY_INV`
  - [x] `DELTA`

**Comment by tarcieri** [comment]
Separately, it would be good to cross-check the constants in `k256`

**Comment by str4d** [comment]
Here are some example tests for the constants: https://github.com/zkcrypto/ff/blob/e853770f4843e47cd5e07330140b5bd1cdfc9f11/tests/derive.rs#L40-L75

The constant in the last check is `t = (p - 1) >> s`.

**Comment by tarcieri** [comment]
@str4d thanks for the pointer. Opened https://github.com/RustCrypto/elliptic-curves/pull/737

**Comment by tarcieri** [comment]
Remaining constants were backfilled and tested in #737
