### ISSUE TITLE
Serde support for k256::schnorr::VerifyingKey

### ISSUE THREAD

**Issue by ycscaly** [RustCrypto/elliptic-curves#745]
Whilst there is serde support for the ecdsa verifying key, and for the underlying curve point & scalar - the schnorr structs do not implement it. They do implement a `to_bytes()` but I believe it is helpful to keep a unified interface.

**Comment by tarcieri** [comment]
Yes, this would be good to add

**Comment by ycscaly** [comment]
Would you like me to do a PR, or do it internally?

**Comment by tarcieri** [comment]
A PR would be good
