### ISSUE TITLE
`Serialize` and `Deserialize` implementation for ECDSA `VerifyingKey` was (accidentally?)  removed

### ISSUE THREAD

**Issue by your-sudden-death** [RustCrypto/elliptic-curves#753]
The `serde` feature does not activate `Serialize` or `Deserialize` for `VerifyingKey`, as the corresponding code has been removed (by accident?) and docs are not updated.

![image](https://user-images.githubusercontent.com/65440078/218220371-2a4fcc0e-6973-4394-b555-275e506463c7.png)

**Comment by tarcieri** [comment]
I think what changed is it now requires the `pem` feature.

That's not entirely ideal. We'll try to get that fixed in the next release so you don't need to enable anything more than `serde`.

**Comment by tarcieri** [comment]
I fixed the upstream issue here: https://github.com/RustCrypto/traits/pull/1245

Unfortunately it won't be available until the next minor release of the `elliptic-curve` crate.

In the meantime, try activating the `pem` feature.
