### ISSUE TITLE
Unable to load key

### ISSUE THREAD

**Issue by fmorency** [RustCrypto/elliptic-curves#769]
Occasionally, our macOS CI generates keys that `p256` cannot load.

Minimal reproducible example: https://github.com/fmorency/p256-error-pem

The failure never happens on our Linux CI. 

Both keys look fine in `openssl` (Linux)
```
openssl ec -in src/key/good.pem -text -noout
read EC key
Private-Key: (256 bit)
priv:
    2e:44:f0:cd:5d:22:61:94:87:9b:7c:78:62:14:c3:
    a7:69:be:04:be:65:01:1c:70:6b:f6:ca:69:79:5c:
    e5:bb
pub:
    04:5d:e0:55:29:ee:a7:7c:8b:96:25:33:02:44:3b:
    68:eb:37:c8:5a:dc:fa:2a:f1:06:e8:5d:8c:13:89:
    f6:c9:db:54:41:17:2c:ce:a9:3a:04:e0:b8:23:55:
    6e:44:f6:b0:e6:1d:a3:27:63:25:cb:a5:21:ea:10:
    08:73:ce:59:be
ASN1 OID: prime256v1
NIST CURVE: P-256

```

```
openssl ec -in src/key/bad.pem -text -noout
read EC key
Private-Key: (256 bit)
priv:
    00:8e:65:1e:5c:28:55:5b:eb:c1:35:ef:ca:e7:59:
    41:cf:f1:54:2d:7f:30:d8:81:7f:3d:23:f5:53:f2:
    28:e1
pub:
    04:32:2a:48:64:da:11:f8:33:44:06:f5:a9:32:a1:
    f8:0f:6e:61:91:84:7e:ba:89:29:dc:23:d1:33:62:
    54:13:b2:b7:fc:15:98:73:a8:ef:b1:f5:6a:1a:e5:
    a8:f8:52:90:a3:9f:8f:e3:10:e7:ed:86:5f:b8:e7:
    7b:47:ea:9a:fd
ASN1 OID: prime256v1
NIST CURVE: P-256
```

**Comment by tarcieri** [comment]
@fmorency I'm going to handle this case, but I'm curious what was generating these keys?

They appear to be invalid, per the SEC1 v2.0 specification:

> The component privateKey is the private key defined to be the octet string of length
[log₂𝑛/8] (where 𝑛 is the order of the curve) obtained from the unsigned integer via the
encoding of Section 2.3.7.

**Comment by fmorency** [comment]
Thanks @tarcieri 

The faulty keys are generated by

`ssh-keygen -a 100 -q -P "" -m pkcs8 -t ecdsa -f output.pem`

on macOS "Ventura" (dev mac-mini)
```
% sw_vers 
ProductName:		macOS
ProductVersion:		13.0.1
BuildVersion:		22A400

% ssh -V
OpenSSH_9.0p1, LibreSSL 3.3.6
```

and macOS "Monterey" (circleCI)
```
% sw_vers 
ProductName:	macOS
ProductVersion:	12.3.1
BuildVersion:	21E258

% ssh -V
OpenSSH_8.6p1, LibreSSL 3.3.5
```

Most of the keys generated using this command are fine. The faulty keys are occasional.

**Comment by tarcieri** [comment]
This problem would be expected for every 1/256 keys, where the leading byte of the private scalar is all zero.

Curious if Linux is using OpenSSL proper which might suggest it's a LibreSSL bug.

**Comment by fmorency** [comment]
We never saw this issue on Linux, and all our Linux systems are using OpenSSL, e.g.,
```
$ ssh -V
OpenSSH_9.2p1, OpenSSL 3.0.8 7 Feb 2023
```

I'm tempted to say it looks like a LibreSSL-related issue.
