### ISSUE TITLE
How to covert `r` and `s` field with type ScalarCore<C> in `Signature` to array of bytes?

### ISSUE THREAD

**Issue by yaoxin1995** [RustCrypto/elliptic-curves#776]
Hey, I want to use `p384` crate to generate a signature, and convert it's `r` and `s` fields to 2 vectors of `u8`, 

Do you have any idea how I can do it?

For example:
```
pub struct Signature {
    pub r: Vec<u8>,
    pub s: Vec<u8>,
    reserved: Vec<u8>,
}

const EMULATED_VCEK: &[u8; 32] = b"a very simple secret key to use!";


let signing_key = SigningKey::from_bytes(EMULATED_VCEK).unwrap(); // Serialize with `::to_bytes()`
let message = b"ECDSA proves knowledge of a secret number in the context of a single message";
let signature: Signature = signing_key.sign(message);

let r = signature.r();
let s = signature.s();

let signature = Signature {
      r: r, 
      s:s,
      reserved: vec::New(),
}         



```

**Comment by tarcieri** [comment]
You can use [`signature.split_bytes()`](https://docs.rs/ecdsa/latest/ecdsa/struct.Signature.html#method.split_bytes) to split it into the `r` and `s` components as `FieldBytes`.

Or call [`to_bytes`](https://docs.rs/elliptic-curve/0.13.1/elliptic_curve/struct.ScalarPrimitive.html#method.to_bytes) to serialize a component.
