### ISSUE TITLE
Public key cryptographic algorithm SM2 based on elliptic curves

### ISSUE THREAD

**Issue by MaxKingPor** [RustCrypto/elliptic-curves#795]
Will it be realized
[openssl SM2](https://www.openssl.org/docs/man1.1.1/man7/SM2.html)
[GmSSL](https://github.com/guanzhi/GmSSL)

**Comment by tarcieri** [comment]
I added it to our tracking list in #114

**Comment by tarcieri** [comment]
Released: https://crates.io/crates/sm2/0.13.0

**Comment by MaxKingPor** [comment]
@tarcieri I see that the document you are using is paid, this is a free document in China
[GM/T 0003-2012 SM2 elliptic curve public key cryptography standard English text release](http://www.gmbz.org.cn/main/postDetail.html?id=20180724110812)

**Comment by tarcieri** [comment]
I mostly used https://datatracker.ietf.org/doc/html/draft-shen-sm2-ecdsa-02 FWIW.

The other citations are just for the canonical definitions for use in standards, since unfortunately there is no RFC to cite (only the I-D above)
