### ISSUE TITLE
unresolved import `p256::ecdh`: could not find `ecdh` in `p256`

### ISSUE THREAD

**Issue by Sarkoxed** [RustCrypto/elliptic-curves#887]
I'm trying to use ecdh functionality, however it can't be found. On the other hand ecdsa is on it's place.
I was following this [guide](https://docs.rs/p256/latest/p256/ecdh/index.html);

Am I missing something in import?

**Comment by tarcieri** [comment]
Per the rustdoc, you need to enable the `ecdh` crate feature:

https://docs.rs/p256/latest/p256/ecdh/index.html

<img width="457" alt="Screenshot 2023-04-26 at 7 04 43 AM" src="https://user-images.githubusercontent.com/797/234583826-cd0d38ae-2eb8-45c5-9b47-f4e5bf1a4f5b.png">
