### ISSUE TITLE
Tweaking a pubkey using a scalar

### ISSUE THREAD

**Issue by alfred-hodler** [RustCrypto/elliptic-curves#896]
First of all, thanks for writing and maintaining this project.

I'm trying to move away from libsecp256k1in favor of this crate but I'm having trouble replicating one part of functionality that the former offers.

Using libsecp256k1, I'm able to tweak a secp256k1 public key using a private key:
```rust
let secp = secp256k1::Secp256k1::new();
let tweaked = pk.mul_tweak(&secp, &(*sk).into())?; // sk is a private key that has the role of a scalar here
```
The resulting `tweaked` is still a pubkey. I'm then able to do `tweaked.serialize_uncompressed()` to get the tweaked pubkey in the SEC1 serialized format, 65 bytes long. This is required by a 3rd party product which is unfortunately rolling its own flavor of ECDH.

Using this crate, perhaps due to my limited understanding of it, I'm only able to get to this point:

```rust
let ss = k256::ecdh::diffie_hellman(sk.to_nonzero_scalar(), pk.as_affine());
let tweaked = ss.raw_secret_bytes().as_slice();
```

`tweaked` here seems to be 32 bytes long and doesn't appear to be a pubkey that I can serialize to uncompressed 65 bytes.

Is there anything I can do to get the outcome that libsecp256k1 gives me?

**Comment by tarcieri** [comment]
The core operation you want is scalar multiplication:

```rust
let tweaked = pk.as_affine() * *sk.to_nonzero_scalar();
```

**Comment by alfred-hodler** [comment]
Thank you, that gets me to a pretty good place.

```rust
let tweaked_pt = *pk.as_affine() * *sk.to_nonzero_scalar();
let tweaked_pk = k256::PublicKey::from_affine(tweaked_pt.to_affine())?;
```

Unfortunately it seems that calling `tweaked_pk.to_sec1_bytes()` can produce only a compressed, 33 byte long representation. Is there a way to get an uncompressed one?
