### ISSUE TITLE
k256: missing check in `PrehashVerifier` impl for `schnorr::VerifyingKey`?

### ISSUE THREAD

**Issue by fjarri** [RustCrypto/elliptic-curves#915]
In [BIP-340](https://github.com/bitcoin/bips/blob/master/bip-0340.mediawiki#verification), the verification checks include:
- Fail if is_infinite(R).
- Fail if not has_even_y(R).
- Fail if x(R) ≠ r.

In https://github.com/RustCrypto/elliptic-curves/blob/5c829a47c076ff9df4fc790f7bb14c2ccf73a5a5/k256/src/schnorr/verifying.rs#L61 we only do the second and the third check, but not the first. Is it intentional?

**Comment by tarcieri** [comment]
The first check does indeed appear to be missing
